-- Crear tabla mdl_sepeservice_centro
CREATE TABLE mdl_sepeservice_centro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ORIGEN_CENTRO VARCHAR(2) NOT NULL,
  CODIGO_CENTRO VARCHAR(10) NOT NULL,
  NOMBRE_CENTRO VARCHAR(40) NOT NULL,
  URL_PLATAFORMA TEXT NOT NULL,
  URL_SEGUIMIENTO TEXT NOT NULL,
  TELEFONO VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  FECHA_CREACION BIGINT(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_tutor_empresa
CREATE TABLE mdl_sepeservice_tutor_empresa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
  NUM_DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
  LETRA_NIF CHAR(1) DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_tutor_formador
CREATE TABLE mdl_sepeservice_tutor_formador (
  id INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_DOCUMENTO VARCHAR(1) NOT NULL,
  NUM_DOCUMENTO VARCHAR(20) NOT NULL,
  LETRA_NIF CHAR(1) NOT NULL,
  ACREDITACION_TUTOR VARCHAR(500) DEFAULT NULL,
  EXPERIENCIA_PROFESIONAL VARCHAR(3) DEFAULT '0',
  COMPETENCIA_DOCENTE VARCHAR(3) DEFAULT NULL,
  EXPERIENCIA_MODALIDAD_TELEFORMACION VARCHAR(3) DEFAULT NULL,
  FORMACION_MODALIDAD_TELEFORMACION VARCHAR(3) DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_accion_formativa
CREATE TABLE mdl_sepeservice_accion_formativa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ORIGEN_ACCION VARCHAR(10) NOT NULL,
  CODIGO_ACCION VARCHAR(20) NOT NULL UNIQUE,
  SITUACION VARCHAR(10) NOT NULL,
  ORIGEN_ESPECIALIDAD VARCHAR(10) NOT NULL,
  AREA_PROFESIONAL VARCHAR(50) NOT NULL,
  CODIGO_ESPECIALIDAD VARCHAR(20) NOT NULL,
  DURACION INT NOT NULL,
  FECHA_INICIO VARCHAR(10) NOT NULL,
  FECHA_FIN VARCHAR(10) NOT NULL,
  IND_ITINERARIO_COMPLETO VARCHAR(2) NOT NULL,
  TIPO_FINANCIACION VARCHAR(10) NOT NULL,
  NUMERO_ASISTENTES INT NOT NULL,
  DENOMINACION_ACCION VARCHAR(255) NOT NULL,
  INFORMACION_GENERAL TEXT DEFAULT NULL,
  HORARIOS TEXT DEFAULT NULL,
  REQUISITOS TEXT DEFAULT NULL,
  CONTACTO_ACCION VARCHAR(255) DEFAULT NULL,
  ID_CENTRO INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_CENTRO) REFERENCES mdl_sepeservice_centro(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_centro_presencial
CREATE TABLE mdl_sepeservice_centro_presencial (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ORIGEN_CENTRO VARCHAR(10) NOT NULL,
  CODIGO_CENTRO VARCHAR(20) NOT NULL UNIQUE,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_contrato_formacion
CREATE TABLE mdl_sepeservice_contrato_formacion (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_CONTRATO_CFA VARCHAR(20) NOT NULL,
  CIF_EMPRESA VARCHAR(20) NOT NULL,
  ID_TUTOR_EMPRESA INT DEFAULT NULL,
  ID_TUTOR_FORMACION INT DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_TUTOR_EMPRESA) REFERENCES mdl_sepeservice_tutor_empresa(id) ON DELETE SET NULL,
  FOREIGN KEY (ID_TUTOR_FORMACION) REFERENCES mdl_sepeservice_tutor_formador(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_uso
CREATE TABLE mdl_sepeservice_uso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ACCION_FORMATIVA INT NOT NULL,
  NUM_PARTICIPANTES_M INT DEFAULT 0,
  NUM_ACCESOS_M INT DEFAULT 0,
  DURACION_TOTAL_M INT DEFAULT 0,
  NUM_PARTICIPANTES_T INT DEFAULT 0,
  NUM_ACCESOS_T INT DEFAULT 0,
  DURACION_TOTAL_T INT DEFAULT 0,
  NUM_PARTICIPANTES_N INT DEFAULT 0,
  NUM_ACCESOS_N INT DEFAULT 0,
  DURACION_TOTAL_N INT DEFAULT 0,
  NUM_PARTICIPANTES INT DEFAULT 0,
  NUMERO_ACTIVIDADES_APRENDIZAJE INT DEFAULT 0,
  NUMERO_INTENTOS INT DEFAULT 0,
  NUMERO_ACTIVIDADES_EVALUACION INT DEFAULT 0,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ACCION_FORMATIVA) REFERENCES mdl_sepeservice_accion_formativa(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_especialidad
CREATE TABLE mdl_sepeservice_especialidad (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ORIGEN_ESPECIALIDAD VARCHAR(10) NOT NULL,
  AREA_PROFESIONAL VARCHAR(10) NOT NULL,
  CODIGO_ESPECIALIDAD VARCHAR(20) NOT NULL,
  ID_CENTRO INT NOT NULL,
  FECHA_INICIO VARCHAR(10) NOT NULL,
  FECHA_FIN VARCHAR(10) NOT NULL,
  MODALIDAD_IMPARTICION VARCHAR(20) NOT NULL,
  HORAS_PRESENCIAL INT DEFAULT 0,
  HORAS_TELEFORMACION INT DEFAULT 0,
  ID_CENTRO_PRESENCIAL INT DEFAULT NULL,
  ID_TUTOR_FORMADOR INT DEFAULT NULL,
  ID_USO INT DEFAULT NULL,
  ID_ACCION_FORMATIVA INT DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_CENTRO) REFERENCES mdl_sepeservice_centro(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_CENTRO_PRESENCIAL) REFERENCES mdl_sepeservice_centro_presencial(id) ON DELETE SET NULL,
  FOREIGN KEY (ID_TUTOR_FORMADOR) REFERENCES mdl_sepeservice_tutor_formador(id) ON DELETE SET NULL,
  FOREIGN KEY (ID_USO) REFERENCES mdl_sepeservice_uso(id) ON DELETE SET NULL,
  FOREIGN KEY (ID_ACCION_FORMATIVA) REFERENCES mdl_sepeservice_accion_formativa(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_accion_especialidad
CREATE TABLE mdl_sepeservice_accion_especialidad (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ACCION_FORMATIVA INT NOT NULL,
  ID_ESPECIALIDAD INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ACCION_FORMATIVA) REFERENCES mdl_sepeservice_accion_formativa(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_especialidad_tutor
CREATE TABLE mdl_sepeservice_especialidad_tutor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD INT NOT NULL,
  ID_TUTOR_FORMADOR INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_TUTOR_FORMADOR) REFERENCES mdl_sepeservice_tutor_formador(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_accion_especialidad_tutor
CREATE TABLE mdl_sepeservice_accion_especialidad_tutor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ACCION_FORMATIVA INT NOT NULL,
  ID_ESPECIALIDAD INT NOT NULL,
  ID_TUTOR_FORMADOR INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ACCION_FORMATIVA) REFERENCES mdl_sepeservice_accion_formativa(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_TUTOR_FORMADOR) REFERENCES mdl_sepeservice_tutor_formador(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_especialidad_centro
CREATE TABLE mdl_sepeservice_especialidad_centro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD INT NOT NULL,
  ID_CENTRO_PRESENCIAL INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_CENTRO_PRESENCIAL) REFERENCES mdl_sepeservice_centro_presencial(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_especialidad_uso
CREATE TABLE mdl_sepeservice_especialidad_uso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD INT NOT NULL,
  ID_USO INT NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_USO) REFERENCES mdl_sepeservice_uso(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_participante
CREATE TABLE mdl_sepeservice_participante (
  id INT AUTO_INCREMENT PRIMARY KEY,
  TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
  NUM_DOCUMENTO VARCHAR(20) NOT NULL,
  LETRA_NIF CHAR(1) DEFAULT NULL,
  INDICADOR_COMPETENCIAS_CLAVE VARCHAR(3) DEFAULT '0',
  ID_CONTRATO_FORMACION INT DEFAULT NULL,
  ID_ACCION_FORMATIVA INT DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_CONTRATO_FORMACION) REFERENCES mdl_sepeservice_contrato_formacion(id) ON DELETE SET NULL,
  FOREIGN KEY (ID_ACCION_FORMATIVA) REFERENCES mdl_sepeservice_accion_formativa(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_especialidad_participante
CREATE TABLE mdl_sepeservice_especialidad_participante (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_PARTICIPANTE INT NOT NULL,
  ID_ESPECIALIDAD INT NOT NULL,
  ID_CENTRO_PRESENCIAL INT DEFAULT NULL,
  FECHA_ALTA VARCHAR(10) DEFAULT NULL,
  FECHA_BAJA VARCHAR(10) DEFAULT NULL,
  RESULTADO_FINAL INT DEFAULT 0,
  CALIFICACION_FINAL DECIMAL(5,2) DEFAULT NULL,
  PUNTUACION_FINAL DECIMAL(5,2) DEFAULT NULL,
  FECHA_INICIO VARCHAR(10) DEFAULT NULL,
  FECHA_FIN VARCHAR(10) DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_PARTICIPANTE) REFERENCES mdl_sepeservice_participante(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES mdl_sepeservice_especialidad(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_CENTRO_PRESENCIAL) REFERENCES mdl_sepeservice_centro_presencial(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_tutoria_presencial
CREATE TABLE mdl_sepeservice_tutoria_presencial (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD_PARTICIPANTE INT NOT NULL,
  ID_CENTRO_PRESENCIAL INT NOT NULL,
  FECHA_INICIO VARCHAR(10) NOT NULL,
  FECHA_FIN VARCHAR(10) NOT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD_PARTICIPANTE) REFERENCES mdl_sepeservice_especialidad_participante(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_CENTRO_PRESENCIAL) REFERENCES mdl_sepeservice_centro_presencial(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_evaluacion_final
CREATE TABLE mdl_sepeservice_evaluacion_final (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD_PARTICIPANTE INT NOT NULL,
  ID_CENTRO_PRESENCIAL INT DEFAULT NULL,
  FECHA_INICIO VARCHAR(10) DEFAULT NULL,
  FECHA_FIN VARCHAR(10) DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD_PARTICIPANTE) REFERENCES mdl_sepeservice_especialidad_participante(id) ON DELETE CASCADE,
  FOREIGN KEY (ID_CENTRO_PRESENCIAL) REFERENCES mdl_sepeservice_centro_presencial(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Crear tabla mdl_sepeservice_resultados
CREATE TABLE mdl_sepeservice_resultados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ID_ESPECIALIDAD_PARTICIPANTE INT NOT NULL,
  RESULTADO_FINAL INT DEFAULT NULL,
  CALIFICACION_FINAL DECIMAL(5,0) DEFAULT NULL,
  PUNTUACION_FINAL DECIMAL(5,0) DEFAULT NULL,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_ESPECIALIDAD_PARTICIPANTE) REFERENCES mdl_sepeservice_especialidad_participante(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

